// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: room.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace NetMessage
{

    [global::ProtoBuf.ProtoContract()]
    public partial class C2SEnterRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class S2CEnterRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class C2SMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class S2CMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"dirx")]
        public float Dirx { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"diry")]
        public float Diry { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"movetime")]
        public long Movetime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class S2CEnterView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"radius")]
        public float Radius { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"spriteid")]
        public long Spriteid { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"speed")]
        public float Speed { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"dir")]
        public Vector2 Dir { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"movetime")]
        public long Movetime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class S2CLeaveView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class S2CUpdateRadius : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"radius")]
        public float Radius { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class S2CDead : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
