--- <auto-generated>
---     Generated by the moonfly tool.  DO NOT EDIT!
--- </auto-generated>

local M={
    C2SLogin = 1,
    S2CLogin = 2,
    C2SMatch = 3,
    C2SEnterRoom = 4,
    C2SMove = 5,
    S2CMatch = 6,
    S2CMatchSuccess = 7,
    S2CEnterRoom = 8,
    S2CMove = 9,
    S2CEnterView = 10,
    S2CLeaveView = 11,
    S2CUpdateRadius = 12,
    S2CDead = 13,
    S2CErrorCode = 14,
    S2CGameOver = 15,

}

local forward = {
    C2SLogin = 'addr_user',
    C2SMatch = 'addr_center',
    C2SEnterRoom = 'addr_room',
    C2SMove = 'addr_room',

}

local mt = { forward = forward }

mt.__newindex = function(_, name, _)
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

mt.__index = function(_, name)
    if name == "forward" then
        return forward
    end
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

return setmetatable(M,mt)
